### PR TITLE
use --undefined to force symbol inclusion for lld

### PR DESCRIPTION
**Pull request by tofay**
Per [zulip](https://rust-lang.zulipchat.com/#narrow/stream/146229-wg-secure-code/topic/rust-audit.20real.20world.20experience) discussion.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Unfortunately this only gets us part of the way there. What if the system `ld` is actually `lld` ? Then the parameter to rustc is not going to be passed explicitly, so we won't be able to detect it, and the build will still fail.

A more robust approach would be actually calling the linker with `--help`, seeing if it supports `--require-defined`, using that if it does, and `--undefined` otherwise.

This raises the question of how do we even tell what the linker is... looks like we'll have to parse the rustc arguments here as well, see if a linker has been passed explicitly, and use that if it was; otherwise use the default. This sounds daunting, but parsing rustc args should be fairly easy thanks to `pico-args`.

**Comment by Shnatsel** [comment]
Alternatively, we can just always use `--undefined` and hand-roll the check equivalent to `--require-defined` - check if the section is present and if not, report an error.

**Comment by tofay** [comment]
or we just use `--undefined` and rely on the fact we have provided the symbol in the object file we created? I think that would suffice if we have CI tests with various linkers

**Comment by Shnatsel** [comment]
Yeah, let's just do that and see if we can compensate with CI or post-build checks or some such. This should be good enough to unblock further iteration on this, at any rate. I'll push that change momentarily.

**Comment by Shnatsel** [comment]
Pushed to master in 284ebd1eae81b166c0165ef1a68d52a4e54635e3. I'll go ahead and close this.

**Comment by Shnatsel** [comment]
Even though the PR is closed, you identifying the issue and proposing a solution really helped! So thanks a lot!

**Pull request closed without merging**
